---
abstract: 'Redis::CappedCollection module provides the fixed sized collections that have a auto-FIFO age-out feature.'
author:
  - 'TrackingSoft LLC <sgladkov@trackingsoft.com>'
build_requires:
  Net::EmptyPort: '0'
  Test::Exception: '0.31'
  Test::RedisServer: '0.04'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Redis-CappedCollection
no_index:
  directory:
    - t
    - inc
    - xt
provides:
  Redis::CappedCollection:
    file: lib/Redis/CappedCollection.pm
    version: 0.14_1
requires:
  Data::UUID: '1.217'
  Digest::SHA1: '2.13'
  Mouse: '0.97'
  Params::Util: '1.07'
  Redis: '1.963'
  Try::Tiny: '0.18'
  perl: '5.010'
version: 0.14_1
